TeamTracker/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using TeamTracker.Data;
using TeamTracker.Models;

namespace TeamTracker.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;
		private readonly TeamTrackerContext _context;

		public HomeController(TeamTrackerContext context)
        {
			_context = context;
        }

        public async Task<IActionResult> Index()
		{
            return View(await _context.project_member.Where(x => x.user_ID == _context.LoggedUserId).Select(y => y.Project).ToListAsync());
        }

        public IActionResult AboutUs()
        {
            return View();
		}
		public async Task<IActionResult> Content()
        {
			return View(await _context.project_member.Where(x => x.user_ID == _context.LoggedUserId).Select(y => y.Project).ToListAsync());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeamTracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TeamTracker.Data;
using TeamTracker.Models;

namespace TeamTracker.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly TeamTrackerContext _context;

        public ProjectsController(TeamTrackerContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Project.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.project_code == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("project_code,project_name")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("project_code,project_name")] Project project)
        {
            if (id != project.project_code)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.project_code))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.project_code == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Project.FindAsync(id);
            if (project != null)
            {
                _context.Project.Remove(project);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Project.Any(e => e.project_code == id);
        }
        // GET Project/Join
        public IActionResult Join()
        {
            return View();
        }
    }
}

TeamTracker/Controllers/WorkSpaceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Evaluation;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using TeamTracker.Data;
using TeamTracker.Models;

namespace TeamTracker.Controllers;

public class WorkSpaceController : Controller
{
	private readonly TeamTrackerContext _context;
	private Models.Project? proj;
	public WorkSpaceController(TeamTrackerContext context)
	{
		_context = context;
		proj = new Models.Project();
	}
	public async Task<IActionResult> Space(int? id)
	{
		if (id == null)
		{
			return NotFound();
		}

		proj = await _context.Project
			.FirstOrDefaultAsync(m => m.project_code == id);

		proj.Phase = _context.Phase.Where(x => x.project_code == id).ToList();
		if (proj == null)
		{
			return NotFound();
		}

		return View(proj);
	}
	public IActionResult appendTasks(int? givenPhaseId)
	{
		var tasksList = _context.Task.Where(t => t.ph_ID == givenPhaseId).Select(x => x).ToList();
		return PartialView("_appendTasks", tasksList);
	}
	public IActionResult appendPhaseInfo(int givenPhaseId)
	{
		var targetPhase = _context.Phase.FirstOrDefault(x => x.PH_ID == givenPhaseId);
		targetPhase.Materials = new List<materials>();
		targetPhase.Materials = _context.materials.Where(m => m.ph_ID == givenPhaseId).Select(x => x).ToList();
		return PartialView("_appendPhaseInfo", targetPhase);
	}
	public IActionResult appendTaskInfo(int givenTaskeId)
	{
		var targetTask = _context.Task.FirstOrDefault(x => x.task_ID == givenTaskeId);
		targetTask.Materials = _context.materials.Where(mat => mat.task_ID == givenTaskeId).Select(x => x).ToList();
		return PartialView("_appendTaskInfo", targetTask);
	}


	public IActionResult editPhase(int givenPhaseId)
	{
		var targetPhase = _context.Phase.FirstOrDefault(x => x.PH_ID == givenPhaseId);
		return PartialView("_editPhase", targetPhase);
	}


	// POST: WorkSpace/editPhase/5
	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> editPhase([Bind("PH_ID, pairant_PH, ParentPhasePH_ID, project_code, phase_name, ph_description, start_date, end_date")] Phase phase)
	{
		if (ModelState.IsValid)
		{
			try
			{
				_context.Update(phase);
				await _context.SaveChangesAsync();
			}
			catch (DbUpdateConcurrencyException)
			{
				return Json(new { html = Helper.RenderRazorViewToString(this, "_editPhase", phase) });
			}
			// After finishing the edit phase
			return Json(new { html = Helper.RenderRazorViewToString(this, "_appendPhaseInfo", phase) });

		}
		// if mode not valied
		return Json(new { html = Helper.RenderRazorViewToString(this, "_editPhase", phase) });
	}
	public async Task<IActionResult> deletePhase(int givenPhaseId)
	{
		var phase = await _context.Phase.FirstOrDefaultAsync(x => x.PH_ID == givenPhaseId);
		try
		{
			RemoveChildsPhase(phase);
			_context.Remove(phase);
            _context.SaveChanges();
			phase.Project = await _context.Project.FirstOrDefaultAsync(x => x.project_code == phase.project_code);
			return Json(new { html = Helper.RenderRazorViewToString(this, "Space", phase.Project) });
		}
		catch
		{
			return Json(new { html = Helper.RenderRazorViewToString(this, "_editPhase", phase) });
		}
	}
	public void RemoveChildsPhase(Phase p)
	{
		try
		{
			p.ChildPhases = _context.Phase.Where(x => x.pairant_PH == p.PH_ID).ToList();

			if (p.ChildPhases != null)
			{
				foreach (var ch in p.ChildPhases)
				{
					RemoveChildsPhase(ch);
					_context.Remove(ch);
				}
			}
		}
		catch
		{
			return;
		}
		
	}
}

TeamTracker/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<div class="text-center">

    <div class="title">
        <h4>Our Team Section</h4>
    </div>

    <div class="d-flex gap-3 my-3 mx-auto card_Container" style="width: fit-content;">

        <div class="card shadow">
            <div class="imbBx shadow">
                <img width="240" height="400" src="~/img/ourTeam/Ammar.jpg" alt="">
            </div>

            <div class="content">
                <div class="contentBx">
                    <h3>Ammar Ahmed <br><span>Creative Leader</span></h3>
                </div>
                <ul class="sci">
                    <li style="--i: 1">
                        <a href="https://www.instagram.com/ammar_0mran/"><i class="fa-brands fa-instagram"></i></a>
                    </li>
                    <li style="--i: 2">
                        <a href="https://github.com/ammar180"><i class="fa-brands fa-github"></i></a>
                    </li>
                    <li style="--i: 3">
                        <a href="https://www.linkedin.com/in/ammar-ahmed-353043264/"><i class="fa-brands fa-linkedin-in"></i></a>
                    </li>
                </ul>
            </div>

        </div>
        <div class="card">

            <div class="imbBx">
               <img width="240" height="400" src="~/img/ourTeam/Ahmed.jpg" alt="">
            </div>

            <div class="content">
                <div class="contentBx">
                    <h3>Ahmed Moustafa <br><span>UI/UX Designer</span></h3>
                </div>
                <ul class="sci">
                    <li style="--i: 1">
                        <a href="https://www.instagram.com/ahmeed_musttafa_/"><i class="fa-brands fa-instagram"></i></a>
                    </li>
                    <li style="--i: 2">
                        <a href="https://github.com/ahmed77mostafa"><i class="fa-brands fa-github"></i></a>
                    </li>
                    <li style="--i: 3">
                        <a href="https://www.linkedin.com/in/ahmed-mostafa-259327268/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"><i class="fa-brands fa-linkedin-in"></i></a>
                    </li>
                </ul>
            </div>

        </div>


        <div class="card">

            <div class="imbBx">
               <img width="240" height="400" src="~/img/ourTeam/Magdy.jpg" alt="">
            </div>

            <div class="content">
                <div class="contentBx">
                    <h3>Magdy Emad <br><span>Web Developer</span></h3>
                </div>
                <ul class="sci">
                    <li style="--i: 1">
                        <a href="#"><i class="fa-brands fa-instagram"></i></a>
                    </li>
                    <li style="--i: 2">
                        <a href="https://github.com/MagdyEm3d"><i class="fa-brands fa-github"></i></a>
                    </li>
                    <li style="--i: 3">
                        <a href="https://www.linkedin.com/in/magdy-emad-371698263/"><i class="fa-brands fa-linkedin-in"></i></a>
                    </li>
                </ul>
            </div>

        </div>

        <div class="card">

            <div class="imbBx">
               <img width="240" height="400" src="~/img/ourTeam/Abrar.jpg" alt="">
            </div>

            <div class="content">
                <div class="contentBx">
                    <h3>Abrar Hamdy <br><span>Front-End Web Developer</span></h3>
                </div>
                <ul class="sci">
                    <li style="--i: 1">
                        <a href="https://www.instagram.com/ah4996319/?igsh=ZWRtMmY0eGl5azNt"><i class="fa-brands fa-instagram"></i></a>
                    </li>
                    <li style="--i: 2">
                        <a href="https://github.com/abrarhamdy111"><i class="fa-brands fa-github"></i></a>
                    </li>
                    <li style="--i: 3">
                        <a href="https://www.linkedin.com/in/abrar-hamdy-ah792007/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"><i class="fa-brands fa-linkedin-in"></i></a>
                    </li>
                </ul>
            </div>

        </div>

        <div class="card">

            <div class="imbBx">
               <img width="240" height="400" src="~/img/ourTeam/Donia.jpg" alt="">
            </div>

            <div class="content">
                <div class="contentBx">
                    <h3>Donia  <br><span>Back-End Web Developer</span></h3>
                </div>
                <ul class="sci">
                    <li style="--i: 1">
                        <a href="https://www.instagram.com/doniaelsatar/?igsh=MWFkazN2ZXBrMzBhYg%3D%3D"><i class="fa-brands fa-instagram"></i></a>
                    </li>
                    <li style="--i: 2">
                        <a href="https://github.com/DoniaAbdelsatar"><i class="fa-brands fa-github"></i></a>
                    </li>
                    <li style="--i: 3">
                        <a href="https://www.linkedin.com/in/donia-abd-elsatar-9bb621281/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"><i class="fa-brands fa-linkedin-in"></i></a>
                    </li>
                </ul>
            </div>

        </div>
    </div>

</div>

TeamTracker/Views/Home/Content.cshtml
@model IEnumerable<TeamTracker.Models.Project>

@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<img src="~/img/logo-teamWork.png" width="300" height="200"/>
	<div class="rounded p-3 py-5 mx-auto" style="width:fit-content; background-color:#a962ef;">
		<h4 class="text-center text-light">Do you have teammates?</h4>
		<div class="dropdown mt-4">
			<a class="btn btn-warning btn-lg" asp-controller="Projects" asp-action="Join">Join Project</a>
			<a class="btn btn-info btn-lg mx-3" asp-controller="Projects" asp-action="Create">New Project</a>
			<a class="dropdown-toggle btn btn-primary btn-lg rounded" data-bs-toggle="dropdown" href="#" role="button"
			   aria-haspopup="true" aria-expanded="false">My Projects</a>
			<div class="dropdown-menu rounded shadow">
				@foreach (var item in Model)
				{
						<a asp-controller="WorkSpace" asp-action="Space" asp-route-id="@item.project_code" class="dropdown-item btn">
						@Html.DisplayFor(modelItem => item.project_name)
						</a>
				}
			</div>
		</div>

	</div>
</div>

TeamTracker/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "WELCOME";
}

<section>
    <div class="welcome-text">
      <h1>
        Welcome To <span>Team Tracker</span>
      </h1>
    <a href="/Home/Content"> <button id="go-register" style="display: none;">Continue</button></a>
    </div>
</section>

@section Scripts{
	<script>
        document.addEventListener('DOMContentLoaded', () => {
        setTimeout(() => {
        document.getElementById('go-register').style.display = 'inline-block';
        }, 5000); 
        });
           document.querySelector('.footer').style.display = 'none';
               document.querySelector('.mt-100p').style.margin = '0';
        document.querySelector('header').style.display = 'none';

	</script>
}