TeamTracker/Controllers/ArticlesController.cs
using Microsoft.AspNetCore.Mvc;

namespace TeamTracker.Controllers
{
    public class ArticlesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult BMC()
        {
            return View();
        }
        public IActionResult POMODORO()
        {
            return View();
        }
        public IActionResult Software()
        {
            return View();
        }
        public IActionResult Deployment()
        {
            return View();
        }
        public IActionResult WebDevelopment()
        {
            return View();
        }

    }
}

TeamTracker/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TeamTracker.Data;
using TeamTracker.Models;

namespace TeamTracker.Controllers
{
    public class UsersController : Controller
    {
        private readonly TeamTrackerContext _context;

        public UsersController(TeamTrackerContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Profile()
        {
            var user = await _context.User
                .FirstOrDefaultAsync(m => m.user_ID == _context.LoggedUserId);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/SignUp
        public IActionResult SignUp()
        {
            return View();
        }

        // POST: Users/SignUp
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp([Bind("user_ID,user_name,public_username,email,user_password,profileIcon_URL,birth_date")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("user_ID,user_name,public_username,email,user_password,profileIcon_URL,birth_date")] User user)
        {
            if (id != user.user_ID)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.user_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.user_ID == id);
        }
    }
}

TeamTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Team Tracker - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/bootstrap-icons/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TeamTracker.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
	<header class="position-fixed top-0 start-0 end-0 z-3">
		<nav class="navbar navbar-expand-lg bg-body-tertiary shadow-sm mb-3 px-10">
        <div class="container-fluid">
            <a class="logo" asp-area="" asp-controller="Home" asp-action="Index"></a>
                
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor04" aria-controls="navbarColor04" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor04">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item me-2">
                        <a class="btn btn-outline-primary rounded border-0" asp-area="" asp-controller="Home" asp-action="Content">Home</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="btn btn-outline-primary rounded border-0" asp-area="" asp-controller="Articles" asp-action="Index">Articles</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="btn btn-outline-primary rounded border-0" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                    </li>
                </ul>

                <div class="d-flex gap-2 align-items-center">
                    <i class="bi bi-bell curs-p me-3 hover-primary" style="font-size: 2rem"></i>
                    <div class="dropdown">
                            <img src="~/img/3dAvatare.png" class="dropdown-toggle img-fluid rounded-circle" width="40" height="40" data-bs-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                        <div class="menu shadow dropdown-menu mt-4 dropdown-menu-end rounded transition p-0">
                            <a asp-controller="Users" asp-action="Profile" class="dropdown-item btn"><i class="bi bi-person-circle me-2"></i>Profile</a>
                            <a asp-controller="Users" asp-action="SignUp" class="dropdown-item btn text-info"></i>Switch Account</a>
                            <a class="dropdown-item btn" href="#"><i class="bi bi-sliders me-2"></i>Setting</a>
                            <a class="dropdown-item btn" href="#"><i class="bi bi-question-circle me-2"></i>Support</a>
							<a class="dropdown-item btn" href="#"><i class="bi bi-box-arrow-right me-2 text-danger"></i><strong class="text-danger">Logout</strong></a>
                            <button class="btn-upgrade rounded-bottom">
                                <i class="animation"></i>UPGRADE NOW!<i class="animation"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </nav>
    </header>

    <div class="mt-100p">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="border-top footer text-muted w-100 p-3">
        &copy; 2024 - Team Tracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>